# templates/qdrant/qdrant-storage-persistentvolumeclaim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-qdrant-storage
  labels:
    app: {{ .Release.Name }}-qdrant-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.qdrant.storageSize | default "100Mi" }}
status: {}
