apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-redis
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    app: {{ .Release.Name }}-redis
status:
  loadBalancer: {}
