apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-llm-server
  labels:
    app: {{ .Release.Name }}-llm-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-llm-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-llm-server
    spec:
      imagePullSecrets:
        - name: ecr_secret
      containers:
        - name: llm-server
          image: {{ .Values.llmServer.image.repository }}:{{ .Values.llmServer.image.tag }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-llm-server-configmap
          ports:
            - containerPort: 8002
              hostPort: 8002
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /app/shared_data
              name: shared-data
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8002
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8002
            initialDelaySeconds: 10
            periodSeconds: 30
      restartPolicy: Always
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: shared-data
