# templates/llm-server/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-llm-server
  labels:
    app: {{ .Release.Name }}-llm-server
spec:
  ports:
    - name: "8002"
      port: 8002
      targetPort: 8002
  selector:
    app: {{ .Release.Name }}-llm-server
