apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-selenium
  labels:
    app: {{ .Release.Name }}-selenium
spec:
  ports:
    - name: "4444"
      port: 4444
      targetPort: 4444
    - name: "7900"
      port: 7900
      targetPort: 7900
  selector:
    app: {{ .Release.Name }}-selenium
