apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-workers
  labels:
    app: {{ .Release.Name }}-workers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-workers
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-workers
    spec:
      imagePullSecrets:
        - name: ecr_secret
      containers:
        - image: {{ .Values.llmServer.image.repository }}:{{ .Values.llmServer.image.tag }}
          args:
            - sh
            - -c
            - celery -A celery_app worker --loglevel=info
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-llm-server-configmap
          name: workers
          resources: {}
          volumeMounts:
            - mountPath: /app/shared_data
              name: shared-data
      restartPolicy: Always
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: shared-data
